### ISSUE TITLE
Export Changes blocked by Chrome

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-plugin-changes#8]
We offer to Export Changes store in browser local storage by constructing and then viewing a data url with the local changes encoded as export format json. This mimics the export functionality for ordinary pages implemented on the server.

https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM

> Summary
> We intend to block web pages from loading data: URLs in the top frame using <A> tags, window.open, window.location and similar mechanisms.
> 
> Motivation
> data: URLs are generally a source of confusion for users. Because of their unfamiliarity and ability to encode arbitrary untrusted content in a URL, they are widely being used in spoofing and phishing attacks. Another problem is that they can be passed along without a backing page that runs JavaScript (e.g. a data URL can be sent via email). For that reason, we intend to block top-frame navigations to data URLs.

The post goes on to explain that downloading from data urls will still be permitted. This might be a preferred alternative, even for the server-side implementation.

The Export Changes functionality was introduced last summer as a way to retrieve content authored over a site that was not owned by the author. https://github.com/fedwiki/wiki-plugin-changes/commit/51e63f12ae44b19e59d562cb3f2ea7ee498c3eec

**Comment by paul90** [comment]
#9 updates the code to download the file, rather than opening the json file in the browser.
